services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - DB_HOST=mariadb
            - DB_PORT=${DB_PORT:-3306}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
            - FROM_NAME=${FROM_NAME}
            - FROM_EMAIL=${FROM_EMAIL}
            - ADMIN_EMAIL=${ADMIN_EMAIL}
        env_file:
            - .env
        depends_on:
            mariadb:
                condition: service_healthy
        networks:
            - app-network

    mariadb:
        image: mariadb:11.4
        container_name: consulta_sociedade_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MARIADB_CHARACTER_SET_SERVER: utf8mb4
            MARIADB_COLLATE_SERVER: utf8mb4_unicode_ci
            MARIADB_INIT_CONNECT: 'SET NAMES utf8mb4;'
        env_file:
            - .env
        ports:
            - '${DB_PORT:-3306}:3306'
        volumes:
            - mariadb_data:/var/lib/mysql
            - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
        networks:
            - app-network
        healthcheck:
            test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3

    adminer:
        image: adminer:4.8.1
        container_name: consulta_sociedade_adminer
        restart: unless-stopped
        ports:
            - '8080:8080'
        environment:
            ADMINER_DEFAULT_SERVER: mariadb
        depends_on:
            - mariadb
        networks:
            - app-network

volumes:
    mariadb_data:
        driver: local

networks:
    app-network:
        driver: bridge
